using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VitaTop.ServiceModel;

namespace VitaTop.WS
{
    public class DataSeeder
    {
        //public static List<string> IngSeedSql()
        //{
        //    List<string> sqls = new List<string>();
        //    var ing = IngSeed();
        //    foreach (var item in ing)
        //    {
        //        var sql = "insert into ingredients(name,portion,units,calories,protien,fat,carb,fiber,satfat) values ('{0}',{1},'gms',{2},{3},{4},{5},{6},{7})";
        //        sql = string.Format(sql, item.Name, item.Portion, item.Calories, item.Protein, item.Fat, item.Carb, item.Fiber, item.SatFat);
        //        sqls.Add(sql);
        //    }

        //    return sqls;
        //}

//        public static List<Ingredients> IngSeed()
//        {
//            var ingredients = new List<Ingredients> {
//new Ingredient {Name = "7 spices", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "almonds", Portion = 1, Calories = 6.48, Protein = 0.18,	Fat = 0.54, Carb = 0.16, Fiber = 0.1, SatFat = 0.01},
//new Ingredient {Name = "anis", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "apple", Portion = 1, Calories = 0.49, Protein = 0,	Fat = 0, Carb = 0.12, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "apricot", Portion = 1, Calories = 0.49, Protein = 0.01,	Fat = 0, Carb = 0.11, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "artichoke", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Arugula", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0.25},
//new Ingredient {Name = "asparagus", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "avocado", Portion = 1, Calories = 1.6, Protein = 0.02,	Fat = 0.147, Carb = 0.085, Fiber = 0.067, SatFat = 0.021},
//new Ingredient {Name = "bagel", Portion = 1, Calories = 1.929, Protein = 0.05,	Fat = 0.013, Carb = 0.413, Fiber = 0.015, SatFat = 0.008},
//new Ingredient {Name = "baguette", Portion = 1, Calories = 1.667, Protein = 0.05,	Fat = 0, Carb = 0.38, Fiber = 0.015, SatFat = 0},
//new Ingredient {Name = "baking powder", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "bakle", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "banana", Portion = 1, Calories = 0.7, Protein = 0.01,	Fat = 0, Carb = 0.16, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "basil", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "bay leaves", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "bay leaves", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "beef fillet", Portion = 1, Calories = 1.15, Protein = 0.19,	Fat = 0.04, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "beef steak lean", Portion = 1, Calories = 1.64, Protein = 0.15,	Fat = 0.11, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "beef very lean", Portion = 1, Calories = 1.09, Protein = 0.22,	Fat = 0.02, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "beetroot", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Bicarbonate", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "biscuit", Portion = 1, Calories = 2.6, Protein = 0.2,	Fat = 0.081, Carb = 0.387, Fiber = 0.097, SatFat = 0.03},
//new Ingredient {Name = "black currant", Portion = 1, Calories = 0.53, Protein = 0.01,	Fat = 0, Carb = 12, Fiber = 0.07, SatFat = 0},
//new Ingredient {Name = "black pepper", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "blackberry", Portion = 1, Calories = 0.41, Protein = 0.01,	Fat = 0, Carb = 0.09, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "blueberry", Portion = 1, Calories = 0.57, Protein = 0.01,	Fat = 0, Carb = 0.13, Fiber = 0.05, SatFat = 0},
//new Ingredient {Name = "bouillon", Portion = 1, Calories = 2.4, Protein = 0.15,	Fat = 0.1, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "bread crumbs", Portion = 1, Calories = 3.58, Protein = 0.13,	Fat = 0.01, Carb = 0.72, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "bread roll", Portion = 1, Calories = 2.76, Protein = 0.07,	Fat = 0.01, Carb = 0.58, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "bresaola", Portion = 1, Calories = 1.829, Protein = 0.36,	Fat = 0.04, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "brioche", Portion = 1, Calories = 2.048, Protein = 0.057,	Fat = 0.02, Carb = 0.422, Fiber = 0.015, SatFat = 0.001},
//new Ingredient {Name = "broccoli", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "brown loaf", Portion = 1, Calories = 2.246, Protein = 0.055,	Fat = 0.047, Carb = 0.387, Fiber = 0.01, SatFat = 0.003},
//new Ingredient {Name = "brown sugar", Portion = 1, Calories = 3.66, Protein = 0,	Fat = 0, Carb = 0.96, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "burger bread", Portion = 1, Calories = 2.791, Protein = 0.095,	Fat = 0.044, Carb = 0.495, Fiber = 0.021, SatFat = 0.012},
//new Ingredient {Name = "butter", Portion = 1, Calories = 7.76, Protein = 0.01,	Fat = 0.83, Carb = 0, Fiber = 0, SatFat = 0.03},
//new Ingredient {Name = "Butter", Portion = 1, Calories = 4, Protein = 0.05,	Fat = 0.7, Carb = 0, Fiber = 0, SatFat = 0.1},
//new Ingredient {Name = "butter light", Portion = 1, Calories = 3.17, Protein = 0,	Fat = 0.35, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "buttermilk", Portion = 1, Calories = 0.42, Protein = 0.04,	Fat = 0.01, Carb = 0.04, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cabbage", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cabbage", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "calamari", Portion = 1, Calories = 0.59, Protein = 0.12,	Fat = 0.01, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "canola oil", Portion = 1, Calories = 8.8, Protein = 0,	Fat = 1, Carb = 0, Fiber = 0, SatFat = 0.07},
//new Ingredient {Name = "caraway seeds", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Carrots", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cashew nuts", Portion = 1, Calories = 5.87, Protein = 0.18,	Fat = 0.42, Carb = 0.3, Fiber = 0.03, SatFat = 0.07},
//new Ingredient {Name = "celery", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "chalendula", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "chamomile", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "chard (seleq)", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cheddar cheese", Portion = 1, Calories = 4, Protein = 0.25,	Fat = 0.321, Carb = 0, Fiber = 0, SatFat = 0.214},
//new Ingredient {Name = "cheddar cheese light", Portion = 1, Calories = 3, Protein = 0.3,	Fat = 0.2, Carb = 0.033, Fiber = 0, SatFat = 0.117},
//new Ingredient {Name = "cheese cream", Portion = 1, Calories = 2.85, Protein = 0.14,	Fat = 0.24, Carb = 0.01, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "cheese emental light", Portion = 1, Calories = 4.02, Protein = 0.28,	Fat = 0.3, Carb = 0.02, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "cheese feta light", Portion = 1, Calories = 2.33, Protein = 0.23,	Fat = 0.16, Carb = 0, Fiber = 0, SatFat = 0.11},
//new Ingredient {Name = "Cheese Halloum", Portion = 1, Calories = 3, Protein = 0.2,	Fat = 0.24, Carb = 0.01, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "cheese parmesan light", Portion = 1, Calories = 3.33, Protein = 0.46,	Fat = 0.16, Carb = 0.06, Fiber = 0, SatFat = 0.1},
//new Ingredient {Name = "cherry", Portion = 1, Calories = 0.57, Protein = 0.01,	Fat = 0, Carb = 0.13, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "chestnut", Portion = 1, Calories = 1.94, Protein = 0.03,	Fat = 0.01, Carb = 0.42, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "chick peas dry", Portion = 1, Calories = 3.11, Protein = 0.2,	Fat = 0.03, Carb = 0.49, Fiber = 0.1, SatFat = 0},
//new Ingredient {Name = "chicken breast", Portion = 1, Calories = 0.75, Protein = 0.16,	Fat = 0.01, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "chicken drumsticks", Portion = 1, Calories = 0.8, Protein = 0.15,	Fat = 0.02, Carb = 0, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "chicken sausage", Portion = 1, Calories = 1.12, Protein = 0.16,	Fat = 0.05, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "chilli sauce", Portion = 1, Calories = 0.652, Protein = 0.02,	Fat = 0, Carb = 0.12, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "chocolate", Portion = 1, Calories = 6, Protein = 0.06,	Fat = 0.26, Carb = 0.6, Fiber = 0.06, SatFat = 0.13},
//new Ingredient {Name = "ciabatta focacia", Portion = 1, Calories = 2.053, Protein = 0.05,	Fat = 0.042, Carb = 0.38, Fiber = 0.015, SatFat = 0.001},
//new Ingredient {Name = "cilantro", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cinamon", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cinamon sticks", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "clementine", Portion = 1, Calories = 0.37, Protein = 0.01,	Fat = 0, Carb = 0.08, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "clove", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "clover seeds", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cocoa powder", Portion = 1, Calories = 4.7, Protein = 0.02,	Fat = 0.25, Carb = 0.38, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "coconut flakes", Portion = 1, Calories = 4.59, Protein = 0.02,	Fat = 0.18, Carb = 0.69, Fiber = 0.04, SatFat = 0.01},
//new Ingredient {Name = "coconut oil", Portion = 1, Calories = 9.25, Protein = 0.01,	Fat = 0.99, Carb = 0, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "coconuts", Portion = 1, Calories = 0.402, Protein = 0.04,	Fat = 0.37, Carb = 0.1, Fiber = 0.09, SatFat = 0.01},
//new Ingredient {Name = "coriander", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "corn", Portion = 1, Calories = 3.41, Protein = 0.09,	Fat = 0.04, Carb = 0.65, Fiber = 0.09, SatFat = 0.02},
//new Ingredient {Name = "cornflakes", Portion = 1, Calories = 3.82, Protein = 0.08,	Fat = 0.02, Carb = 0.83, Fiber = 0.04, SatFat = 0.01},
//new Ingredient {Name = "cornstarch", Portion = 1, Calories = 3.57, Protein = 0,	Fat = 0, Carb = 0.87, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "couscous", Portion = 1, Calories = 4, Protein = 0.176,	Fat = 0.035, Carb = 0.845, Fiber = 0.106, SatFat = 0},
//new Ingredient {Name = "crackers", Portion = 1, Calories = 5.229, Protein = 0,	Fat = 0.294, Carb = 0.654, Fiber = 0, SatFat = 0.065},
//new Ingredient {Name = "cranberries", Portion = 1, Calories = 0.37, Protein = 0,	Fat = 0, Carb = 0.09, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "creme fraiche", Portion = 1, Calories = 3.93, Protein = 0.02,	Fat = 0.4, Carb = 0.03, Fiber = 0, SatFat = 0.02},
//new Ingredient {Name = "creme fraiche light", Portion = 1, Calories = 1.6, Protein = 0.03,	Fat = 0.15, Carb = 0.05, Fiber = 0, SatFat = 0.003},
//new Ingredient {Name = "cucumber", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "cumin", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "curry powder", Portion = 1, Calories = 3.5, Protein = 0.15,	Fat = 0.15, Carb = 0.6, Fiber = 0.35, SatFat = 0},
//new Ingredient {Name = "dates (dried)", Portion = 1, Calories = 2.75, Protein = 0.02,	Fat = 0, Carb = 0.65, Fiber = 0.09, SatFat = 0},
//new Ingredient {Name = "dill", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "dried fig", Portion = 1, Calories = 6, Protein = 0.18,	Fat = 0.56, Carb = 0.16, Fiber = 0.1, SatFat = 0.01},
//new Ingredient {Name = "Dry apricot", Portion = 1, Calories = 3, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "dry mint", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "egg", Portion = 1, Calories = 1.6, Protein = 0.13,	Fat = 0.11, Carb = 0.01, Fiber = 0, SatFat = 0.02},
//new Ingredient {Name = "egg plant", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "egg white", Portion = 1, Calories = 0.49, Protein = 0.11,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "egg yolk", Portion = 1, Calories = 3.63, Protein = 0.16,	Fat = 0.32, Carb = 0, Fiber = 0, SatFat = 0.06},
//new Ingredient {Name = "elderberry", Portion = 1, Calories = 0.41, Protein = 0.03,	Fat = 0, Carb = 0.07, Fiber = 0.04, SatFat = 0},
//new Ingredient {Name = "endives", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "fennel seeds", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "fenugreek", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "fish - cod", Portion = 1, Calories = 0.7, Protein = 0.17,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "fish - sole", Portion = 1, Calories = 0.59, Protein = 0.12,	Fat = 0.01, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "foccacia bread", Portion = 1, Calories = 2.857, Protein = 0.082,	Fat = 0.061, Carb = 0.51, Fiber = 0.02, SatFat = 0.005},
//new Ingredient {Name = "frankfurter sausages", Portion = 1, Calories = 2.49, Protein = 0.13,	Fat = 0.21, Carb = 0, Fiber = 0, SatFat = 0.02},
//new Ingredient {Name = "garlic", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Ginger", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "ginger bread", Portion = 1, Calories = 3.064, Protein = 0.064,	Fat = 0.072, Carb = 0.531, Fiber = 0.01, SatFat = 0.002},
//new Ingredient {Name = "grapefruit", Portion = 1, Calories = 0.33, Protein = 0.01,	Fat = 0, Carb = 0.07, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "grapes", Portion = 1, Calories = 0.7, Protein = 0.01,	Fat = 0, Carb = 0.16, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "green beans", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "green pepper", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "groats (burghol)", Portion = 1, Calories = 3.45, Protein = 0.12,	Fat = 0.026, Carb = 0.75, Fiber = 0.1, SatFat = 0.006},
//new Ingredient {Name = "ground beef", Portion = 1, Calories = 2.12, Protein = 0.2,	Fat = 0.14, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "hazel nuts", Portion = 1, Calories = 6.87, Protein = 0.14,	Fat = 0.62, Carb = 0.13, Fiber = 0.07, SatFat = 0.2},
//new Ingredient {Name = "henna", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "henna", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "hibiscus", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "honey", Portion = 1, Calories = 3.32, Protein = 0,	Fat = 0, Carb = 0.81, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "jam", Portion = 1, Calories = 2.71, Protein = 0,	Fat = 0, Carb = 0.66, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "jello", Portion = 1, Calories = 4.762, Protein = 0.476,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "jewsmallow (mouloukhia)", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "kaki", Portion = 1, Calories = 0.74, Protein = 0.01,	Fat = 0, Carb = 0.17, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "ketchup", Portion = 1, Calories = 1.07, Protein = 0.02,	Fat = 0, Carb = 0.24, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "kiwi", Portion = 1, Calories = 0.53, Protein = 0.01,	Fat = 0, Carb = 0.12, Fiber = 0.07, SatFat = 0},
//new Ingredient {Name = "kusain", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "lebanese bread", Portion = 1, Calories = 2.892, Protein = 0.097,	Fat = 0.013, Carb = 0.575, Fiber = 0.012, SatFat = 0},
//new Ingredient {Name = "leek", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0.25},
//new Ingredient {Name = "lemon", Portion = 1, Calories = 0.25, Protein = 0.01,	Fat = 0, Carb = 0.05, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "lentils dry", Portion = 1, Calories = 3.37, Protein = 0.24,	Fat = 0.01, Carb = 0.56, Fiber = 0.11, SatFat = 0},
//new Ingredient {Name = "lettuce", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mache", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mango", Portion = 1, Calories = 0.49, Protein = 0.01,	Fat = 0, Carb = 0.11, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "margarine", Portion = 1, Calories = 3.97, Protein = 0.06,	Fat = 0.04, Carb = 0, Fiber = 0, SatFat = 0.12},
//new Ingredient {Name = "marjoram", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "marzipan", Portion = 1, Calories = 4.99, Protein = 0.08,	Fat = 0.25, Carb = 0.57, Fiber = 0.01, SatFat = 0.05},
//new Ingredient {Name = "mascarpone cheese", Portion = 1, Calories = 4.65, Protein = 0.036,	Fat = 0.5, Carb = 0.036, Fiber = 0, SatFat = 0.368},
//new Ingredient {Name = "mayonnaise", Portion = 1, Calories = 5.08, Protein = 0.01,	Fat = 0.52, Carb = 0.05, Fiber = 0, SatFat = 0.32},
//new Ingredient {Name = "mayonnaise light", Portion = 1, Calories = 3.26, Protein = 0,	Fat = 0.33, Carb = 0.12, Fiber = 0, SatFat = 0.05},
//new Ingredient {Name = "meat veal", Portion = 1, Calories = 0.94, Protein = 0.16,	Fat = 0.03, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "melon", Portion = 1, Calories = 0.25, Protein = 0.01,	Fat = 0, Carb = 0.05, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "milk 0.03%", Portion = 1, Calories = 0.44, Protein = 0.05,	Fat = 0.03, Carb = 0.05, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "milk caramel", Portion = 1, Calories = 4.03, Protein = 0.03,	Fat = 0.05, Carb = 0.84, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "milk full fat", Portion = 1, Calories = 0.67, Protein = 0.033,	Fat = 0.039, Carb = 0, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "milk low fat", Portion = 1, Calories = 0.51, Protein = 0.04,	Fat = 0.015, Carb = 0.05, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mimolette cheese", Portion = 1, Calories = 3.571, Protein = 0.25,	Fat = 0.25, Carb = 0, Fiber = 0, SatFat = 0.143},
//new Ingredient {Name = "mint", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mortadella", Portion = 1, Calories = 3.47, Protein = 0.12,	Fat = 0.32, Carb = 0, Fiber = 0, SatFat = 0.03},
//new Ingredient {Name = "mouloukhia", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mozarella light", Portion = 1, Calories = 2.54, Protein = 0.24,	Fat = 0.15, Carb = 0.02, Fiber = 0, SatFat = 0.02},
//new Ingredient {Name = "muesli dry", Portion = 1, Calories = 4.05, Protein = 0.09,	Fat = 0.1, Carb = 0.67, Fiber = 0.05, SatFat = 0},
//new Ingredient {Name = "mushroom", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "mustard", Portion = 1, Calories = 0.5, Protein = 0,	Fat = 0, Carb = 0.1, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "naan bread", Portion = 1, Calories = 1.865, Protein = 0.05,	Fat = 0.015, Carb = 0.397, Fiber = 0.015, SatFat = 0},
//new Ingredient {Name = "nachos", Portion = 1, Calories = 3.36, Protein = 0.009,	Fat = 0.212, Carb = 0.354, Fiber = 0.018, SatFat = 0.071},
//new Ingredient {Name = "nectarine", Portion = 1, Calories = 0.7, Protein = 0.01,	Fat = 0, Carb = 0.16, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "noodles", Portion = 1, Calories = 1.1, Protein = 0.01,	Fat = 0.003, Carb = 0.25, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "nutella", Portion = 1, Calories = 5.3, Protein = 0.068,	Fat = 0.31, Carb = 0.56, Fiber = 0.04, SatFat = 0.103},
//new Ingredient {Name = "oats", Portion = 1, Calories = 3.69, Protein = 0.13,	Fat = 0.07, Carb = 0.61, Fiber = 0.06, SatFat = 0.04},
//new Ingredient {Name = "oats (shoufan)", Portion = 1, Calories = 0.7, Protein = 0.01,	Fat = 0.01, Carb = 0.12, Fiber = 0.01, SatFat = 0.002},
//new Ingredient {Name = "ognion", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "okra", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "olive", Portion = 1, Calories = 1.34, Protein = 0.01,	Fat = 0.14, Carb = 0, Fiber = 0.02, SatFat = 0.01},
//new Ingredient {Name = "olive oil", Portion = 1, Calories = 9.3, Protein = 0,	Fat = 1, Carb = 0, Fiber = 0, SatFat = 0.08},
//new Ingredient {Name = "orange", Portion = 1, Calories = 0.41, Protein = 0.01,	Fat = 0, Carb = 0.09, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "Oregano", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pain de campagne", Portion = 1, Calories = 1.869, Protein = 0.061,	Fat = 0.004, Carb = 0.41, Fiber = 0.015, SatFat = 0},
//new Ingredient {Name = "pain de mie", Portion = 1, Calories = 1.882, Protein = 0.059,	Fat = 0.013, Carb = 0.37, Fiber = 0.012, SatFat = 0.003},
//new Ingredient {Name = "papaya", Portion = 1, Calories = 0.33, Protein = 0,	Fat = 0, Carb = 0.08, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "paprika", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "paprika", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "parsley", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "passion fruit", Portion = 1, Calories = 0.57, Protein = 0,	Fat = 0, Carb = 0.08, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "pasta", Portion = 1, Calories = 3.76, Protein = 0.13,	Fat = 0.03, Carb = 0.72, Fiber = 0.03, SatFat = 0.01},
//new Ingredient {Name = "peach", Portion = 1, Calories = 0.45, Protein = 0.01,	Fat = 0, Carb = 0.1, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "peanut butter", Portion = 1, Calories = 5.875, Protein = 0.25,	Fat = 0.503, Carb = 0.197, Fiber = 0.059, SatFat = 0.106},
//new Ingredient {Name = "pear", Portion = 1, Calories = 0.57, Protein = 0.01,	Fat = 0, Carb = 0.13, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "peas", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "peas dry", Portion = 1, Calories = 3.41, Protein = 0.22,	Fat = 0.01, Carb = 0.59, Fiber = 0.12, SatFat = 0.01},
//new Ingredient {Name = "peppermint", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pesto sauce", Portion = 1, Calories = 3.167, Protein = 0.067,	Fat = 0.3, Carb = 0.033, Fiber = 0, SatFat = 0.05},
//new Ingredient {Name = "philadelphia cheese light", Portion = 1, Calories = 1.55, Protein = 0.082,	Fat = 0.115, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pickles", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pine nuts", Portion = 1, Calories = 6.6, Protein = 0.13,	Fat = 0.7, Carb = 0.13, Fiber = 0.033, SatFat = 0.05},
//new Ingredient {Name = "pineapple", Portion = 1, Calories = 0.29, Protein = 0,	Fat = 0, Carb = 0.07, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "pistachio", Portion = 1, Calories = 6.19, Protein = 0.21,	Fat = 0.52, Carb = 0.12, Fiber = 0.07, SatFat = 0.07},
//new Ingredient {Name = "pitta bread", Portion = 1, Calories = 2.121, Protein = 0.05,	Fat = 0.042, Carb = 0.397, Fiber = 0.015, SatFat = 0.003},
//new Ingredient {Name = "plums", Portion = 1, Calories = 0.62, Protein = 0.01,	Fat = 0, Carb = 0.14, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "pomegranate", Portion = 1, Calories = 0.37, Protein = 0,	Fat = 0, Carb = 0.09, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "popcorn sweet", Portion = 1, Calories = 4.2, Protein = 0.13,	Fat = 0.05, Carb = 0.78, Fiber = 0.04, SatFat = 0.02},
//new Ingredient {Name = "porridge oats", Portion = 1, Calories = 3.93, Protein = 0.14,	Fat = 0.07, Carb = 0.66, Fiber = 0.07, SatFat = 0.04},
//new Ingredient {Name = "potatoes with peel", Portion = 1, Calories = 0.7, Protein = 0.02,	Fat = 0, Carb = 0.15, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "potatoes without peel", Portion = 1, Calories = 0.86, Protein = 0.02,	Fat = 0, Carb = 0.19, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "powder sugar", Portion = 1, Calories = 4, Protein = 0,	Fat = 0, Carb = 1, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pralines", Portion = 1, Calories = 4.56, Protein = 0.05,	Fat = 0.7, Carb = 0.16, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "prawns", Portion = 1, Calories = 0.87, Protein = 0.19,	Fat = 0.01, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "pretzel", Portion = 1, Calories = 1.76, Protein = 0.052,	Fat = 0.002, Carb = 0.397, Fiber = 0.015, SatFat = 0},
//new Ingredient {Name = "pudding", Portion = 1, Calories = 0.8, Protein = 0.026,	Fat = 0.026, Carb = 0.01, Fiber = 0.035, SatFat = 0.018},
//new Ingredient {Name = "puff pastry baked goods", Portion = 1, Calories = 4.35, Protein = 0.08,	Fat = 0.3, Carb = 0.3, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "pumpkins", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Purslane", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "raddish", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "raisins", Portion = 1, Calories = 2.71, Protein = 0.02,	Fat = 0, Carb = 0.64, Fiber = 0.05, SatFat = 0},
//new Ingredient {Name = "raisins (dry)", Portion = 1, Calories = 3.25, Protein = 0.025,	Fat = 0, Carb = 0.775, Fiber = 0.05, SatFat = 0},
//new Ingredient {Name = "raspberry", Portion = 1, Calories = 0.37, Protein = 0.01,	Fat = 0, Carb = 0.08, Fiber = 0.05, SatFat = 0},
//new Ingredient {Name = "red beans dry", Portion = 1, Calories = 2.643, Protein = 0.221,	Fat = 0.011, Carb = 0.439, Fiber = 0.15, SatFat = 0},
//new Ingredient {Name = "red currant", Portion = 1, Calories = 0.41, Protein = 0.01,	Fat = 0, Carb = 0.09, Fiber = 0.04, SatFat = 0},
//new Ingredient {Name = "red pepper", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "reis polished", Portion = 1, Calories = 3.62, Protein = 0.07,	Fat = 0.01, Carb = 0.79, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "rice uncle ben's", Portion = 1, Calories = 3.46, Protein = 0.08,	Fat = 0.005, Carb = 0.77, Fiber = 0.03, SatFat = 0.0015},
//new Ingredient {Name = "rice white", Portion = 1, Calories = 3.58, Protein = 0.065,	Fat = 0.005, Carb = 0.8, Fiber = 0.03, SatFat = 0.0015},
//new Ingredient {Name = "rice wholemeal", Portion = 1, Calories = 3.55, Protein = 0.07,	Fat = 0.02, Carb = 0.75, Fiber = 0.04, SatFat = 0.01},
//new Ingredient {Name = "rocca", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "rosemary", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "rye whole meal bread", Portion = 1, Calories = 2.27, Protein = 0.07,	Fat = 0.01, Carb = 0.46, Fiber = 0.07, SatFat = 0.01},
//new Ingredient {Name = "safflower seeds", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "salami", Portion = 1, Calories = 5.07, Protein = 0.17,	Fat = 0.47, Carb = 0, Fiber = 0, SatFat = 0.05},
//new Ingredient {Name = "salmon", Portion = 1, Calories = 1.37, Protein = 0.13,	Fat = 0.09, Carb = 0, Fiber = 0, SatFat = 0.05},
//new Ingredient {Name = "salt", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "seeds", Portion = 1, Calories = 5.99, Protein = 0.27,	Fat = 0.49, Carb = 0.08, Fiber = 0.06, SatFat = 0.29},
//new Ingredient {Name = "semisweet chocolate", Portion = 1, Calories = 5.21, Protein = 0.05,	Fat = 0.3, Carb = 0.54, Fiber = 0, SatFat = 0.01},
//new Ingredient {Name = "senna", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "sesame oil", Portion = 1, Calories = 8.9, Protein = 0,	Fat = 1, Carb = 0, Fiber = 0, SatFat = 0.133},
//new Ingredient {Name = "sessame seeds", Portion = 1, Calories = 5.51, Protein = 0.21,	Fat = 0.5, Carb = 0, Fiber = 0.12, SatFat = 0.2},
//new Ingredient {Name = "Shrimps", Portion = 1, Calories = 1, Protein = 0.2,	Fat = 0.02, Carb = 0.01, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "skimmed milk", Portion = 1, Calories = 0.51, Protein = 0.04,	Fat = 0.015, Carb = 0.05, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "sorghum", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "soya beans dry", Portion = 1, Calories = 4.73, Protein = 0.37,	Fat = 0.24, Carb = 0.24, Fiber = 0.12, SatFat = 0.12},
//new Ingredient {Name = "soya oil", Portion = 1, Calories = 9.21, Protein = 0,	Fat = 0.99, Carb = 0, Fiber = 0, SatFat = 0.62},
//new Ingredient {Name = "Soya sauce", Portion = 1, Calories = 2, Protein = 0,	Fat = 0.2, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "soybean sprouts", Portion = 1, Calories = 0.54, Protein = 0.05,	Fat = 0.01, Carb = 0.06, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "spearmint", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "spinach", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "strawberries", Portion = 1, Calories = 0.33, Protein = 0.01,	Fat = 0, Carb = 0.07, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "sugar", Portion = 1, Calories = 4.1, Protein = 0,	Fat = 0, Carb = 1, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "sunflower oil (80% fat)", Portion = 1, Calories = 7.65, Protein = 0.02,	Fat = 0.8, Carb = 0.03, Fiber = 0, SatFat = 0.49},
//new Ingredient {Name = "sunflower seeds", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "sweet potato", Portion = 1, Calories = 0.847, Protein = 0,	Fat = 0, Carb = 0.157, Fiber = 0.014, SatFat = 0},
//new Ingredient {Name = "tangerine", Portion = 1, Calories = 0.37, Protein = 0.01,	Fat = 0, Carb = 0.08, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "tapioca", Portion = 1, Calories = 1.15, Protein = 0.027,	Fat = 0.027, Carb = 0.204, Fiber = 0, SatFat = 0.018},
//new Ingredient {Name = "thyme (zaatar)", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "tomato", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "tomato puree", Portion = 1, Calories = 0.45, Protein = 0.02,	Fat = 0, Carb = 0.09, Fiber = 2, SatFat = 0},
//new Ingredient {Name = "tortilla", Portion = 1, Calories = 2.863, Protein = 0.086,	Fat = 0.061, Carb = 0.496, Fiber = 0, SatFat = 0.008},
//new Ingredient {Name = "tuna", Portion = 1, Calories = 2.39, Protein = 0.22,	Fat = 0.16, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "turkey", Portion = 1, Calories = 1.22, Protein = 0.23,	Fat = 0.03, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "turkish bread", Portion = 1, Calories = 2.543, Protein = 0.083,	Fat = 0.019, Carb = 0.426, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "Turmeric", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "vanilla", Portion = 1, Calories = 2.857, Protein = 0,	Fat = 0, Carb = 0.119, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "vanilla essence", Portion = 1, Calories = 3, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "verbascum", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "vermicelli", Portion = 1, Calories = 3.71, Protein = 0.124,	Fat = 0.018, Carb = 0.742, Fiber = 0.035, SatFat = 0},
//new Ingredient {Name = "vinegar", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "wallnut", Portion = 1, Calories = 7.05, Protein = 0.15,	Fat = 0.63, Carb = 0.14, Fiber = 0.05, SatFat = 0.2},
//new Ingredient {Name = "water", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "watermelon", Portion = 1, Calories = 0.12, Protein = 0,	Fat = 0, Carb = 0.03, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "wheat", Portion = 1, Calories = 3.14, Protein = 0.12,	Fat = 0.02, Carb = 0.6, Fiber = 0.11, SatFat = 0.01},
//new Ingredient {Name = "wheat bran", Portion = 1, Calories = 1.94, Protein = 0.16,	Fat = 0.05, Carb = 0.2, Fiber = 0.42, SatFat = 0.02},
//new Ingredient {Name = "wheat bread", Portion = 1, Calories = 3.26, Protein = 0.1,	Fat = 0.02, Carb = 0.65, Fiber = 0.03, SatFat = 0.01},
//new Ingredient {Name = "wheat flour", Portion = 1, Calories = 3.58, Protein = 0.11,	Fat = 0.01, Carb = 0.74, Fiber = 0.02, SatFat = 0},
//new Ingredient {Name = "wheat mixed grain bread", Portion = 1, Calories = 2.1, Protein = 0.07,	Fat = 0.01, Carb = 0.42, Fiber = 0.04, SatFat = 0.01},
//new Ingredient {Name = "wheat whole meal bread", Portion = 1, Calories = 2.35, Protein = 0.08,	Fat = 0.01, Carb = 0.47, Fiber = 0.07, SatFat = 0},
//new Ingredient {Name = "white beans dry", Portion = 1, Calories = 3.38, Protein = 0.21,	Fat = 0.02, Carb = 0.57, Fiber = 0.17, SatFat = 0},
//new Ingredient {Name = "white bread", Portion = 1, Calories = 1.733, Protein = 0.05,	Fat = 0, Carb = 0.397, Fiber = 0.015, SatFat = 0},
//new Ingredient {Name = "white flour", Portion = 1, Calories = 3.33, Protein = 0.1,	Fat = 0, Carb = 0.76, Fiber = 0.03, SatFat = 0},
//new Ingredient {Name = "white pepper", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "wholemeal bread", Portion = 1, Calories = 1.631, Protein = 0.04,	Fat = 0.047, Carb = 0.252, Fiber = 0.035, SatFat = 0},
//new Ingredient {Name = "wholemeal pasta", Portion = 1, Calories = 3.52, Protein = 0.15,	Fat = 0.03, Carb = 0.64, Fiber = 0.08, SatFat = 0},
//new Ingredient {Name = "worcester sauce", Portion = 1, Calories = 5.2, Protein = 0.06,	Fat = 0.328, Carb = 0.5, Fiber = 0, SatFat = 0.024},
//new Ingredient {Name = "Yeast", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "yellow mustard", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "yellow pepper", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "yellow plum", Portion = 1, Calories = 0.66, Protein = 0.01,	Fat = 0, Carb = 0.15, Fiber = 0.01, SatFat = 0},
//new Ingredient {Name = "Yogurt", Portion = 1, Calories = 0.42, Protein = 0.04,	Fat = 0.04, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "yogurt (low fat)", Portion = 1, Calories = 0.529, Protein = 0.044,	Fat = 0.009, Carb = 0.066, Fiber = 0, SatFat = 0.007},
//new Ingredient {Name = "zaffron", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "zest de citron", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0},
//new Ingredient {Name = "zucchini", Portion = 1, Calories = 0, Protein = 0,	Fat = 0, Carb = 0, Fiber = 0, SatFat = 0}                
//        };

//            return ingredients;
//        }
    }
}